import React from 'react';
import ReactPlayer from 'react-player';


const About = () => {
  return (
    <div className="flex justify-center items-center min-h-screen  p-4">
      <div className="w-full max-w-5xl bg-pink p-8">
        <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-6 text-center text-red-950">About Us</h2>
        <p className="text-gray-700 mb-4">
        CardioScan is an AI-powered heart health solution designed to make ECG analysis fast, accurate, and accessible. Our platform enables users to upload ECG images and receive instant predictions—normal or abnormal—helping in early detection of heart conditions. With a commitment to innovation and accuracy, CardioScan empowers individuals and healthcare professionals with reliable insights for proactive heart care.
        </p>

        {/*  */}
        <div className=" w-full p-5 md:p-10 from-red-300 to-red-50 ">
      
      <div className="flex justify-center items-center m-4 gap-8 md:gap-20">
        <ReactPlayer
          url="/vdo.mp4"
          controls
          width="100%"
          height="auto"
          className="max-w-md"
        />
      </div>
    </div>
        {/*  */}
        
        <h3 className="text-2xl md:text-3xl lg:text-4xl font-bold mb-4 text-red-950">Our Mission</h3>
        <p className="text-gray-700 mb-4">
        To revolutionize heart health monitoring through AI-driven ECG analysis, ensuring early detection, accurate insights, and easy accessibility for everyone, anywhere in the world.
        </p>
        <h3 className="text-2xl md:text-3xl lg:text-4xl font-bold mb-4 text-red-950">Our Vision</h3>
        <p className="text-gray-700 mb-4">
        To create a future where heart health management is seamless, proactive, and technology-driven, reducing the risks of cardiovascular diseases through early diagnosis and accessible digital healthcare solutions.
        </p>
        <h3 className="text-lg md:text-2xl font-bold mb-4 text-red-950">ECG Signals</h3>
        <p className="text-gray-700 mb-4">
          <p className='text-black font-bold text-center mb-7'> How is an ECG Done?</p>
          <img className='h-80 mx-auto' src="h5.webp" alt="" />
        <br/>
An Electrocardiogram (ECG) is a simple, non-invasive test that records the electrical activity of the heart. Small electrode patches are placed on the chest, arms, and legs, which detect the heart’s electrical signals. These signals are then displayed as waveforms on a monitor or printed on paper. The test is quick, painless, and helps doctors assess heart rhythm, detect abnormalities, and diagnose conditions like arrhythmias, heart attacks, or other cardiac issues.
<br/> <br/>
<p className='text-black font-bold text-center mb-7'> What is an ECG Signal?</p>
<img className='h-80 mx-auto' src="pqrs.png" alt="" />

 <br/>

An ECG signal represents the electrical impulses generated by the heart during each heartbeat. It consists of different wave components—P wave, QRS complex, and T wave—each corresponding to specific phases of the cardiac cycle. The P wave indicates atrial contraction, the QRS complex shows ventricular contraction, and the T wave represents ventricular recovery. By analyzing these signals, doctors can evaluate heart function, detect irregularities, and diagnose potential cardiovascular diseases.
<br />
 <h3 className="text-xl md:text-2xl lg:text-3xl font-bold mt-4 mb-4 text-red-950">CardioScan - One beat at a time!</h3>
        </p>
        <p className='text-gray-700'>CardioScan is revolutionizing heart health monitoring with AI-driven ECG analysis, making early detection faster, easier, and more accessible. By simply uploading an ECG image, users receive instant insights, empowering them to take proactive steps toward heart care. Whether for individuals seeking peace of mind or healthcare professionals looking for reliable diagnostic support, CardioScan ensures accuracy, efficiency, and convenience.

With a vision to make heart health management seamless and technology-driven, CardioScan is committed to improving cardiovascular care worldwide. By bridging the gap between advanced medical diagnostics and everyday accessibility, we strive to reduce the risks of heart disease and promote a healthier future for all. Your heart’s health is in your hands—trust CardioScan for timely and accurate insights. ❤️</p>
       <br />
      
      </div>
    </div>
  );
};

export default About;
